In [4]:
import numpy as np

**Valid Sudoku**

In [5]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])

In [6]:
np.sum(s)

np.int64(405)

In [9]:
x=np.sum(s,axis=1)
x

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [11]:
y=np.sum(s,axis=0)
y

array([45, 45, 45, 45, 45, 45, 45, 45, 45])

In [16]:
for i in x:
    if(i!=45):
        print('sudoku is valid')
        break
    else: print('sudoku id valid')

sudoku id valid
sudoku id valid
sudoku id valid
sudoku id valid
sudoku id valid
sudoku id valid
sudoku id valid
sudoku id valid
sudoku id valid


In [15]:
for i in y:
    if(i==45):
        print('sudoku is valid')
    else:
        print('sudoku is not valid')

sudoku is valid
sudoku is valid
sudoku is valid
sudoku is valid
sudoku is valid
sudoku is valid
sudoku is valid
sudoku is valid
sudoku is valid


In [19]:
z=s[0:3,0:3]
z

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [20]:
int(z.sum())

45

In [22]:
for i in range(0,9,3):
    for j in range(0,9,3): 
        n = s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


**General Questions**

In [91]:
import numpy as np

# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [29]:
#Get the shape of the matrix.
np.shape(data)

(5, 3)

In [31]:
#Find the average age of students.
data.mean()

np.float64(61.06666666666667)

In [39]:
#Extract Math marks of all students.
data[:,2]

array([78, 88, 95, 70, 85])

In [40]:
#Find the highest Science mark.
data.max()

np.int64(95)

In [44]:
#Get details of the student who scored more than 90 in Math.
x=data[data[:,1]>90]
x

array([[19, 92, 88]])

In [46]:
#Increase Math marks of all students by 5.
data[:,1]+5

array([90, 97, 81, 70, 95])

In [51]:
#Find how many students are younger than 19.
y = data[data[:,0]>19]
y

array([[20, 90, 85]])

In [56]:
#Calculate the average marks in each subject (column-wise mean).
np.mean(data[:,1:3],axis=0)


array([81.6, 83.2])

In [84]:
#Get data of students who scored at least 80 in both subjects.
data[(data[:,1]>80)&(data[:,2]>80)]

array([[19, 92, 88],
       [20, 90, 85]])

In [92]:
#Replace all Science marks < 75 with 0.
data[:,2][data[:,2]<75]=0

In [93]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 95],
       [18, 65,  0],
       [20, 90, 85]])