In [3]:
import numpy as np

In [14]:
arr1 = np.arange(1,6)
arr2 = np.arange(5,10)


In [21]:
arr1

array([1, 2, 3, 4, 5])

In [22]:
arr2

array([5, 6, 7, 8, 9])

In [15]:
arr+10

array([11, 12, 13, 14, 15])

In [18]:
arr1*arr2

array([ 5, 12, 21, 32, 45])

In [17]:
arr1+arr2

array([ 6,  8, 10, 12, 14])

In [20]:
arr1/arr2

array([0.2       , 0.33333333, 0.42857143, 0.5       , 0.55555556])

In [23]:
arr1//arr2

array([0, 0, 0, 0, 0])

In [24]:
arr2/arr1

array([5.        , 3.        , 2.33333333, 2.        , 1.8       ])

In [25]:
arr2//arr1

array([5, 3, 2, 2, 1])

In [27]:
l = np.arange(1,26).reshape(5,5)
l

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [28]:
l+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [29]:
l*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

In [35]:
arr1 = l[:,0]
arr1

array([ 1,  6, 11, 16, 21])

In [39]:
l[0]*5

array([ 5, 10, 15, 20, 25])

In [44]:
l[0,0:4]

array([1, 2, 3, 4])

In [47]:
b=l.copy()

In [48]:
b[0,0]=10

In [49]:
b

array([[10,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [50]:
l

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [56]:
mat1 = np.arange(0,4).reshape(2,2)
mat2 = np.arange(5,9).reshape(2,2)

In [57]:
mat1

array([[0, 1],
       [2, 3]])

In [58]:
mat2

array([[5, 6],
       [7, 8]])

In [60]:
mat1*mat2

array([[ 0,  6],
       [14, 24]])

In [61]:
mat1@mat2

array([[ 7,  8],
       [31, 36]])

In [62]:
mat1.dot(mat2)

array([[ 7,  8],
       [31, 36]])

In [63]:
mat1.T

array([[0, 2],
       [1, 3]])

In [92]:
arr1 = np.arange(1,7)
arr2 = np.arange(8,14)
arr3 = np.arange(15,21)
arr1

array([1, 2, 3, 4, 5, 6])

In [93]:
arr2

array([ 8,  9, 10, 11, 12, 13])

In [94]:
arr3

array([15, 16, 17, 18, 19, 20])

In [95]:
np.hstack((arr1,arr2,arr3))

array([ 1,  2,  3,  4,  5,  6,  8,  9, 10, 11, 12, 13, 15, 16, 17, 18, 19,
       20])

In [96]:
np.vstack((arr1,arr2,arr3))

array([[ 1,  2,  3,  4,  5,  6],
       [ 8,  9, 10, 11, 12, 13],
       [15, 16, 17, 18, 19, 20]])

In [97]:
np.column_stack((arr1,arr2,arr3))

array([[ 1,  8, 15],
       [ 2,  9, 16],
       [ 3, 10, 17],
       [ 4, 11, 18],
       [ 5, 12, 19],
       [ 6, 13, 20]])

In [4]:
arr3 = np.arange(1,37).reshape(6,6)
arr3

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [126]:
np.hsplit(arr3,3)

[array([[ 1,  2],
        [ 7,  8],
        [13, 14],
        [19, 20],
        [25, 26],
        [31, 32]]),
 array([[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22],
        [27, 28],
        [33, 34]]),
 array([[ 5,  6],
        [11, 12],
        [17, 18],
        [23, 24],
        [29, 30],
        [35, 36]])]

In [133]:
np.vsplit(arr3,3)

[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]]),
 array([[25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36]])]

In [134]:
for i in arr3:
    print(i)


[1 2 3 4 5 6]
[ 7  8  9 10 11 12]
[13 14 15 16 17 18]
[19 20 21 22 23 24]
[25 26 27 28 29 30]
[31 32 33 34 35 36]
