In [3]:
import numpy as np

In [3]:
a1 = np.array([0,1,2,3,4])
a2 = np.array([5,6,7,8,9])
a1

array([0, 1, 2, 3, 4])

In [4]:
a1+a2

array([ 5,  7,  9, 11, 13])

In [5]:
a1-a2

array([-5, -5, -5, -5, -5])

In [6]:
a1*a2

array([ 0,  6, 14, 24, 36])

In [7]:
a1/a2

array([0.        , 0.16666667, 0.28571429, 0.375     , 0.44444444])

In [8]:
a1//a2   #give nearest value like greatest integer  2.555 = 2   or  -2.444 = -3

array([0, 0, 0, 0, 0])

In [9]:
a1**a2

array([     0,      1,    128,   6561, 262144])

In [13]:
l =[10,20,30,40,50]
arr = np.array(l)
arr

array([10, 20, 30, 40, 50])

In [12]:
arr+10   # add the each element by 10

array([20, 30, 40, 50, 60])

In [14]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [15]:
arr2+10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [17]:
arr2*2

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50]])

In [23]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [24]:
a[0:6]

array([1, 2, 3, 4, 5, 6])

In [26]:
a[0:6]*5

array([ 5, 10, 15, 20, 25, 30])

In [27]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [33]:
b=a   # here if we change value in element of array b then automatically change in a  to overcome this problem .copy() is uses

In [34]:
b[0] = 99

In [35]:
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [36]:
b=a.copy()   # here if we change value in array b then in array a not change in .copy()

In [39]:
b[1]=100

In [40]:
b

array([ 99, 100,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20])

In [41]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [43]:
#matrix multiplcation

In [62]:
mat1 = np.arange(0,4).reshape(2,2)
mat2 = np.arange(4,8).reshape(2,2)


In [63]:
mat1

array([[0, 1],
       [2, 3]])

In [64]:
mat2

array([[4, 5],
       [6, 7]])

In [65]:
mat1*mat2  #in it we multiple element to element

array([[ 0,  5],
       [12, 21]])

In [66]:
mat1@mat2  #in it we multiple rows and colums

array([[ 6,  7],
       [26, 31]])

In [70]:
np.dot(mat1,mat2)  # in np.dot is also uses as rows and colums multiplication

array([[ 6,  7],
       [26, 31]])

In [71]:
mat1.T  # T will transpose the matrix

array([[0, 2],
       [1, 3]])

In [ ]:
#stacking array

In [5]:
a=np.array([1,2,3,4])
b=np.array([4,5,6,7])

In [6]:
np.vstack((a,b))  #vertical add arrays

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [8]:
np.hstack((a,b))  #horizontal add arrays

array([1, 2, 3, 4, 4, 5, 6, 7])

In [9]:
np.column_stack((a,b))   #1row->1column ans 2rows->2column

array([[1, 4],
       [2, 5],
       [3, 6],
       [4, 7]])

In [10]:
#spliting array

In [20]:
c = np.arange(1,37).reshape(6,6)
c

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [26]:
np.hsplit(c,3)   #  note -np.hsplit in NumPy is used to split an array horizontally (column-wise) into multiple sub-arrays.
#only split in proper no of cut like 6 is cut by 1,2, 3 or 6 

[array([[ 1,  2],
        [ 7,  8],
        [13, 14],
        [19, 20],
        [25, 26],
        [31, 32]]),
 array([[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22],
        [27, 28],
        [33, 34]]),
 array([[ 5,  6],
        [11, 12],
        [17, 18],
        [23, 24],
        [29, 30],
        [35, 36]])]

In [27]:
np.vsplit(c,3)    #  note -np.hsplit in NumPy is used to split an array vertically (rows-wise) into multiple sub-arrays. 
#only split in proper no of cut like 6 is cut by 1,2, 3 or 6 #(if its a odd no then we whato cut with 2.5)

[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]]),
 array([[25, 26, 27, 28, 29, 30],
        [31, 32, 33, 34, 35, 36]])]

In [32]:
for i in c:
    print(i)

[1 2 3 4 5 6]
[ 7  8  9 10 11 12]
[13 14 15 16 17 18]
[19 20 21 22 23 24]
[25 26 27 28 29 30]
[31 32 33 34 35 36]


In [33]:
for i in a:
    print(i)

1
2
3
4
