In [3]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4])

In [3]:
print(arr)

[1 2 3 4]


In [1]:
a = [5,6,7,8.5,"aryan"]

[5, 6, 7, 8.5, 'aryan']

In [5]:
np.array(a)

array(['5', '6', '7', '8.5', 'aryan'], dtype='<U32')

In [14]:
l = [[1,2,3],[4,5,6],[7,8,9]]

In [15]:
print(l)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [16]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [18]:
arr = np.zeros((6,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
arr = np.ones((3,5))
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
n = np.linspace(0,1,10)     #find the no of element in between to number with proper distance between all
n

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [29]:
np.random.rand(10)       #random give random element and .rand give element in between [0,1)

array([0.08645246, 0.67767455, 0.52202517, 0.25213928, 0.19320733,
       0.73024915, 0.43766505, 0.98884415, 0.81160803, 0.9189885 ])

In [22]:
np.random.randn(10)   #in practice: about 99.7% of the values fall between −3 and +3 (this comes from the 68–95–99.7 rule of normal distribution).

array([ 0.94643973, -0.15623138,  0.51498968, -0.05923386,  1.62890723,
       -1.81277858,  0.18098473,  1.27656378,  0.17139413, -1.42200952])

In [9]:
np.random.randint(56)   #give ramdom no

44

In [24]:
np.random.randint(0,50,10)

array([ 7, 12, 32, 44, 20, 23, 20,  5, 39,  1], dtype=int32)

In [30]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
arr.shape   # no of row and colums

(3, 3)

In [82]:
arr.size    #total elemtnt in array

9

In [83]:
arr.dtype   

dtype('int64')

In [84]:
arr.min()

np.int64(1)

In [71]:
arr.max()

np.int64(9)

In [72]:
arr.sum()

np.int64(45)

In [32]:
np.sum(arr,axis=0)    #axis=0 give total of  no of columns

array([12, 15, 18])

In [33]:
np.sum(arr,axis=1)      #axis=0 give total of no of rows

array([ 6, 15, 24])

In [75]:
arr.mean()    #give mean

np.float64(5.0)

In [76]:
arr.std()    #give std

np.float64(2.581988897471611)

In [78]:
arr.argmax()     #maxmum index

np.int64(8)

In [79]:
arr.argmin()    #min index

np.int64(0)

In [85]:
arr = np.arange(1,31)
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [86]:
arr.reshape(5,6)   #reshape convert in 2d matrix

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])